### ISSUE TITLE
Subscribe response is not a valid JSON

### ISSUE THREAD

**Issue by pct960** [rbccps-iisc/corinthian#63]
If the published messages are in JSON then the subscribe response is not a valid JSON

**Comment by arun-babu** [comment]
Fixed

**Comment by pct960** [comment]
Response is not a JSON. Will fix it in the next few commits.

```
[{"sent-by":"admin/dev","from":"admin/dev.protected","subject"#","content-type":"application/json","body":{ "ambientLux": 10000, "power": 73.26, "caseTemp": 34.5 }}]
```

**Comment by pct960** [comment]
Fixed in https://github.com/rbccps-iisc/corinthian/commit/f5120712b443e488804582d725d842c92db1ff62

**Comment by pct960** [comment]
Response is not valid if the queue is empty. Will fix it in next commit.

**Comment by pct960** [comment]
Fixed in https://github.com/rbccps-iisc/corinthian/pull/102
